# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MDD' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MDD

  pod 'Alamofire', '~> 4.7'
  pod 'NVActivityIndicatorView'
  pod 'IQKeyboardManagerSwift'
  pod 'TPKeyboardAvoidingSwift'
  pod 'SDWebImage', '~> 4.0'
  pod 'PopupDialog'
  pod 'AssetsPickerViewController'
  pod 'MaterialComponents/Snackbar'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod "GSImageViewerController"
  pod 'Fabric', '~> 1.7.2'
  pod 'Crashlytics', '~> 3.9.3'
  pod 'SwiftGifOrigin'





  target 'MDDTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MDDUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
